SAMPLES:
#     [Short] # MET-1-09]
#     [GV01, GV02, GV03, GV04, GV05, GV06, GV07, GV08, GV09, GV10,
#     GV11, GV12, GV13, GV14, GV15, GV16, GV17, GV18, GV19, GV20,
#     GV21, GV22, GV23, GV24, GV25, GV26, GV27, GV28, GV29, GV30,
#     GV31, GV32, GV33, GV34, GV35, GV36, GV37, GV38, GV39, GV40,
#     GV41, GV42, GV43, GV44, GV45, GV46, GV47, GV48,
     [
     BRIP01, BRIP02, BRIP03, BRIP04, BRIP05, BRIP06, BRIP07, BRIP08,
     BRIP15, BRIP16, BRIP17, BRIP18, BRIP19, BRIP20, BRIP21, BRIP22,
     BRIP23, BRIP24, BRIP25, BRIP26, BRIP27, BRIP28, BRIP29, BRIP30,
     BRIP31, BRIP32, BRIP33, BRIP34, BRIP35, BRIP36, BRIP37, BRIP38,
     BRIP39, BRIP40, BRIP41, BRIP42, BRIP43, BRIP44, BRIP45, BRIP46,
     BRIP47, BRIP48, BRIP49, BRIP50, BRIP51, BRIP52, BRIP53, BRIP54,
     BRIP55, BRIP56, BRIP57, BRIP58, BRIP59, BRIP60, BRIP61, BRIP62,
     BRIP63, BRIP64, BRIP65, BRIP66, BRIP67, BRIP68, BRIP69, BRIP70,
     BRIP71, BRIP72, BRIP73, BRIP74, BRIP75, BRIP76, BRIP77, BRIP78,
     BRIP79, BRIP80, BRIP81, BRIP82, BRIP83, BRIP84, BRIP85, BRIP86,
     BRIP87, BRIP88, BRIP89, BRIP90, BRIP91, BRIP92, BRIP93, BRIP94,
     BRIP95, BRIP96, BRIP97, BRIP98, BRIP99, BRIP100, BRIP101, BRIP102,
     BRIP103, BRIP104, BRIP105, BRIP106, BRIP107, BRIP108, BRIP109, BRIP110,
     BRIP111, BRIP112, BRIP113, BRIP114, BRIP115, BRIP116, BRIP117, BRIP118,
     BRIP119, BRIP120, BRIP121, BRIP122, BRIP123, BRIP124, BRIP125, BRIP126,
     BRIP127, BRIP128, BRIP129, BRIP130, BRIP131, BRIP132, BRIP133, BRIP134,
     BRIP135, BRIP136, BRIP137, BRIP145, BRIP146, BRIP147, BRIP148, BRIP149,
     BRIP150, BRIP151, BRIP152, BRIP153, #BRIP154,
     BRIP155, BRIP156, BRIP157,
     BRIP158, BRIP159, BRIP160, BRIP161, BRIP162, BRIP163, BRIP164,
     BRIP165, BRIP166, BRIP167, BRIP168, BRIP169, BRIP170, BRIP171, BRIP172,
     BRIP173, BRIP174, BRIP175, BRIP176, BRIP177, BRIP178, BRIP179, BRIP180,
     BRIP181, BRIP182, BRIP183, BRIP184,
     SSLP_MEYER_IRBHLY1, SSLP_MEYER_IRBHLY2, SSLP_MEYER_IRBHLY3, SSLP_MEYER_IRBHLY4, SSLP_MEYER_IRBHLY5,
     HMCB13, LMCB13, HMCB14, LMCB14, HMCB12, LMCB11, HMCB11, LMCB10, HMCB10,
     LMCB9, HMCB9, LMCB8, HMCB8, LMCB7, HMCB7, LMCB6, HMCB6, LMCB5, HMCB5,
     LMCB4, HMCB4, LMCB3, HMCB3, LMCB1, HMCB1, HMCB15, LMCB15, LMCB16, HMCB16, HMCB17, LMCB17,
     HMCBRIPB18, LMCBRIPB18,
     BRIPHMC10438846, HMCBRIP1038151, HMCBRIP10438511]

EXT:
     ['C2T', 'G2A']

#Locations
CLUSTER: / #default is / for cluster2
DATA: /workdir/apc88/GVHD/Data/
REFERENCES: /workdir/apc88/GVHD/references/
ADAPTOR_SEQUENCES: /workdir/apc88/GVHD/references/adapter_sequences/adapters_meyer.fa
CHROMO_SIZES: /workdir/apc88/GVHD/Data/hg19.chrom.sizes
#References
METHREF: /workdir/apc88/GVHD/references/hg19_Bismark/
BWA_HG19: /workdir/apc88/GVHD/references/hg19/hg19.fa
phiXREF: /workdir/apc88/GVHD/references/phiX_bwa/phiX.fa
GRAMMY_REF_FASTA: /workdir/apc88/GVHD/updated_grammy_wgbs/grammy/NCBIGenomes06_CT #only takes lengths so conversion doesnt matter
# Programs
BBDUK: /workdir/apc88/GVHD/software/bbmap/bbduk.sh
FILTERBYNAME: /workdir/apc88/GVHD/software/bbmap/filterbyname.sh
FLASH: /programs/flash
BISMARK: /workdir/apc88/GVHD/software/Bismark-0.22.1/bismark
INTERLEAVE: /workdir/apc88/GVHD/software/bbmap/reformat.sh
HSBLASTN: /workdir/apc88/GVHD/software/hs-blastn-src/hs-blastn

GRAMMY_RDT: /workdir/apc88/GVHD/software/GRAMMy/grammy/grammy_rdt.py
GRAMMY_PRE: /workdir/apc88/GVHD/software/GRAMMy/grammy/grammy_pre.py
GRAMMY_EM: /workdir/apc88/GVHD/software/GRAMMy/grammy/grammy_em.py
GRAMMY_POST: /workdir/apc88/GVHD/software/GRAMMy/grammy/grammy_post.py

VIRUSES:
     [NC_001538.1, NC_006273.1, NC_001664.4, NC_014407.1, NC_014406.1, NC_000898.1, NC_007605.1]
