SAMPLES:
#     [Short1]
     [
     # BRIP01, BRIP02, BRIP03, BRIP04, BRIP05, BRIP06, BRIP07, BRIP08,
     # BRIP15, BRIP16, BRIP17, BRIP18, BRIP19, BRIP20, BRIP21, BRIP22,
     # BRIP23, BRIP24, BRIP25, BRIP26, BRIP27, BRIP28, BRIP29, BRIP30,
     # BRIP31, BRIP32, BRIP33, BRIP34, BRIP35, BRIP36, BRIP37, BRIP38,
     # BRIP39, BRIP40, BRIP41, BRIP42, BRIP43, BRIP44, BRIP45, BRIP46,
     # BRIP47, BRIP48, BRIP49, BRIP50, BRIP51, BRIP52, BRIP53, BRIP54,
     # BRIP55, BRIP56, BRIP57, BRIP58, BRIP59, BRIP60, BRIP61, BRIP62,
     # BRIP63, BRIP64, BRIP65, BRIP66, BRIP67, BRIP68, BRIP69, BRIP70,
     # BRIP71, BRIP72, BRIP73, BRIP74, BRIP75, BRIP76, BRIP77, BRIP78,
     # BRIP79, BRIP80, BRIP81, BRIP82, BRIP83, BRIP84, BRIP85, BRIP86,
     # BRIP87, BRIP88, BRIP89, BRIP90, BRIP91, BRIP92, BRIP93, BRIP94,
     # BRIP95, BRIP96, BRIP97, BRIP98, BRIP99, BRIP100, BRIP101, BRIP102,
     # BRIP103, BRIP104, BRIP105, BRIP106, BRIP107, BRIP108, BRIP109, BRIP110,
     # BRIP111, BRIP112, BRIP113, BRIP114, BRIP115, BRIP116, BRIP117, BRIP118,
     # BRIP119, BRIP120, BRIP121, BRIP122, BRIP123, BRIP124, BRIP125, BRIP126,
     # BRIP127, BRIP128, BRIP129, BRIP130, BRIP131, BRIP132, BRIP133, BRIP134,
     # BRIP135, BRIP136, BRIP137, BRIP145, BRIP146, BRIP147, BRIP148, BRIP149,
     # BRIP150, BRIP151, BRIP152, BRIP153, BRIP154, BRIP155, BRIP156, BRIP157,
     # BRIP158, BRIP159, BRIP160, BRIP161, BRIP162, BRIP163, BRIP164,
     # BRIP165, BRIP166, BRIP167, BRIP168, BRIP169, BRIP170, BRIP171, BRIP172,
     # BRIP173, BRIP174, BRIP175, BRIP176, BRIP177, BRIP178, BRIP179, BRIP180,
     # BRIP181, BRIP182, BRIP183, BRIP184,
     BRIP156, BRIP114,BRIP21, BRIP132, BRIP89, BRIP66, BRIP133, BRIP46, BRIP113, BRIP163, BRIP70,
     SSLP_MEYER_IRBHLY1, SSLP_MEYER_IRBHLY2, SSLP_MEYER_IRBHLY3, SSLP_MEYER_IRBHLY4, SSLP_MEYER_IRBHLY5,
     # 12417_1252_135355_HN75YBGXH_261M_GCATTGG_CTCTGCA, 12417_1252_135356_HN75YBGXH_31PR_GATCTCG_CCTAGGT, 12417_1252_135357_HN75YBGXH_176M_AGATAGG_GCTCGAA, 12417_1252_135358_HN75YBGXH_31D0_CCGATTG_ACCAACT, 12417_1252_135359_HN75YBGXH_26E_ATGCCGC_CCGGTAC, 12417_1252_135360_HN75YBGXH_26D0_AATAGTA_TTGAAGT, 12417_1252_135361_HN75YBGXH_246M_AGGTACC_TCGCAGG, 12417_1252_135362_HN75YBGXH_26PR_TGCGTCC_CTCTGCA,
     # 12403_1252_135116_HJYGJBGXH_1413_ACGCAAC_TCGCAGG,
     # 12403_1252_135117_HJYGJBGXH_1513_GCATTGG_CTCTGCA,
     # 12403_1252_135118_HJYGJBGXH_1563_GATCTCG_CCTAGGT,
     # 12403_1252_135119_HJYGJBGXH_1564_CAATATG_GGATCAA,
     # 12403_1252_135120_HJYGJBGXH_1567_TGACGTC_GCAAGAT,
     # 12403_1252_135121_HJYGJBGXH_1569_GATGCCA_ATGGAGA,
     # 12403_1252_135122_HJYGJBGXH_1568_CAATTAC_CTCGATG,
     # 12403_1252_135123_HJYGJBGXH_1579_AGATAGG_GCTCGAA,
     # 12403_1252_135124_HJYGJBGXH_1566_CCGATTG_ACCAACT,
     # 12403_1252_135125_HJYGJBGXH_1565_ATGCCGC_CCGGTAC,
     # 12455_1252_136521_HTJWYBGXH_CHSP1_ACGCAAC_TCGCAGG,
     # 12455_1252_136522_HTJWYBGXH_CHSP2_GCATTGG_CTCTGCA,
     # 12455_1252_136523_HTJWYBGXH_CHSP3_GATCTCG_CCTAGGT,
     # 12455_1252_136524_HTJWYBGXH_CHSP4_CAATATG_GGATCAA,
     # 12455_1252_136525_HTJWYBGXH_CHSP5_TGACGTC_GCAAGAT,
     # 12455_1252_136526_HTJWYBGXH_CHSP6_GATGCCA_ATGGAGA
     ]

CONTROLS:
     [HMCBRIP1038151, PHICMCBRIP1043151, LMCB17, HMCB17, LMCB16, HMCB16, LMCB15, HMCB15,
     HMCB13, LMCB13, HMCB14, LMCB14, HMCB12, LMCB11,
     HMCB11, LMCB10, HMCB10, LMCB9, HMCB9, LMCB8, HMCB8,
     LMCB7, HMCB7, LMCB6, HMCB6, LMCB5, HMCB5, LMCB4,
     HMCB4, LMCB3, HMCB3, LMCB1, HMCB1]

READS:
     [R1, R2]

KNOWNCHROMO:
     [chr1, chr2, chr3, chr4, chr5, chr6, chr7, chr8, chr9, chr10, chr11, chr12, chr13, chr14, chr15, chr16, chr17, chr18, chr19, chr20, chr21, chr22, chrX, chrY]

#Locations
CLUSTER: / #default is / for cluster2
DATA: /workdir/apc88/GVHD/Data/
LISTS: /workdir/apc88/GVHD/lists/
REFERENCES: /workdir/apc88/GVHD/references/
REFERENCE_METHYLOMES: /workdir/apc88/GVHD/Reference_Methylomes/MethylMatrix/all_chr/
ADAPTOR_SEQUENCES: /workdir/apc88/GVHD/references/adapter_sequences/adapters_meyer.fa

#References
METHREF: /workdir/apc88/GVHD/references/hg19_Bismark/
HG19: /workdir/apc88/GVHD/references/hg19_Bismark/hg19.fa

CTLREF: /workdir/apc88/GVHD/references/mic_control/
CTLREF_fasta: /workdir/apc88/GVHD/references/mic_control/mic.fa
# Programs
SPRING: /workdir/apc88/GVHD/software/SPRING/build/spring
BBDUK: /workdir/apc88/GVHD/software/bbmap/bbduk.sh
BISMARK: /workdir/apc88/GVHD/software/Bismark-0.22.1/bismark
RMDUPS : /workdir/apc88/GVHD/software/Bismark-0.22.1/deduplicate_bismark
METHEXT: /workdir/apc88/GVHD/software/Bismark-0.22.1/bismark_methylation_extractor

PICARD_MARKDUP: java -jar /workdir/apc88/GVHD/software/picard.jar MarkDuplicates
METHPIPETOMR: /workdir/apc88/GVHD/software/methpipe-3.4.3/bin/to-mr
METHPIPEBSRATE: /workdir/apc88/GVHD/software/methpipe-3.4.3/bin/bsrate
HMMCOPY_READCOUNTER: /workdir/apc88/GVHD/software/HMMcopy/bin/readCounter
SEQTK: /workdir/apc88/GVHD/software/seqtk/seqtk
MOSDEPTH: /workdir/apc88/GVHD/software/mosdepth
# Eilon SCRIPTS_PATH
ddcfDNA: /workdir/apc88/GVHD/software/ddcfDNA/ddcfDNA-master

# Programs
FASTQPAIR : /workdir/apc88/GVHD/software/fastq-pair/build/fastq_pair

#Strings
AUTOSOMALCHROMO: chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22
