channels:
  - conda-forge
  - bioconda
  - r
  - defaults
  - bcbio
dependencies:
  - bcftools=1.6
  - bwa=0.7.12
  - graphviz=2.38.0
  - python=3.6
  - samtools=1.8
  - snakemake=5.4.0
  - pyyaml=3.11
